export const AllData = [
  {
    id: 1,
    img: "/src/assets/images/1.png",
    name: "Stainless Steel Casual Watch for Man SMART Quartz Watches for Boys & Men New Fashion Wrist watch",
    rating: "****",
    oldPrice: "800",
    newPrice: "650",
    color: "Brown Dial, Black Dial",
    tag: "limited",
  },
  {
    id: 2,
    img: "/src/assets/images/2.png",
    name: "M:8456 Curren Black Dial Silver Stainless Steel Chain Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "5500",
    newPrice: "4000",
    color: "Black Dial",
    tag: "limited",
  },
  {
    id: 3,
    img: "/src/assets/images/3.png",
    name: "M:8450 Curren Blue Dial silver Stainless Steel Chain Quartz Analog Men's Watch.",
    rating: "****",
    oldPrice: "6000",
    newPrice: "4300",
    color: "Blue Dial",
    tag: "limited",
  },
  {
    id: 4,
    img: "/src/assets/images/4.png",
    name: "M:8450 Curren green Dial silver Stainless Steel Chain Quartz Analog Men's Watch.",
    rating: "****",
    oldPrice: "5500",
    newPrice: "3900",
    color: "Green Dial",
    tag: "limited",
  },
  {
    id: 5,
    img: "/src/assets/images/5.png",
    name: "M:8457 curren Blue Dial Silver Stainless Steel Chain Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "5500",
    newPrice: "3950",
    color: "Blue Dial",
    tag: "limited",
  },
  {
    id: 6,
    img: "/src/assets/images/6.png",
    name: "M:8363 Curren black Dial Silver Stainless Steel Chronograph Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "8000",
    newPrice: "7000",
    color: "Black Dial",
    tag: "limited",
  },
  {
    id: 7,
    img: "/src/assets/images/7.png",
    name: "MTP-V004L-7CUDF Casio Silver Dial Brown Leather Strap Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "12780",
    newPrice: "10900",
    color: "Silver Dial",
    tag: "limited",
  },
  {
    id: 8,
    img: "/src/assets/images/8.png",
    name: "M:8459 Curren BLACK/GOLD Color Dial Fashion Quartz Clock Analog Chronograph Men's Watch.",
    rating: "****",
    oldPrice: "9750",
    newPrice: "6750",
    color: "Black / Golden Dial",
    tag: "Bestseller",
  },
  {
    id: 9,
    img: "/src/assets/images/9.png",
    name: " M:8458 curren TIFNY Dial SILVER Stainless Steel Chain Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "5500",
    newPrice: "3899",
    color: "TIFNY Dial",
    tag: "Good",
  },
  {
    id: 10,
    img: "/src/assets/images/10.png",
    name: "M:8457 curren Black Dial Silver Stainless Steel Chain Analog Quartz Men's Watch.",
    rating: "****",
    oldPrice: "5600",
    newPrice: "3999",
    color: "Black Dial",
    tag: "Bestseller",
  },
  {
    id: 11,
    img: "/src/assets/images/11.png",
    name: "MTP-1381L-7AVDF Casio Analog Quartz Watch For Men's.",
    rating: "****",
    oldPrice: "19000",
    newPrice: "14000",
    color: "White Dial",
    tag: "New",
  },
];
